map_typ: costmap
obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [[0.2225, 0.2045], [0.2225, -0.2045], [-0.2225, -0.2045], [-0.2225, 0.2405]]
#robot_radius: ir_of_robot
inflation_radius: 0.55
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: car/laser_link , data_type: LaserScan, topic: car/scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}