map_type: costmap
obstacle_range: 0.5
raytrace_range: 6.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [[-0.35, -0.15], [0.35, -0.15], [0.35, 0.15], [-0.35, 0.15]]
#robot_radius: ir_of_robot
inflation_radius: 0.1
observation_sources: laser_scan_sensor
rolling_window: true

# laser_scan_sensor: {sensor_frame: car/laser_link , data_type: LaserScan, topic: scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}