global_costmap:
  global_frame: map
  robot_base_frame: car/base_link
  # update_frequency: 5.0
  # publish_frequency: 2.0
  # planner_frequency: 0.0
  width: 20.0
  height: 20.0
  static_map: false
  rolling_window: true
  # plugins:
  #   - {name: static_layer, type: 'costmap_2d::StaticLayer'}